#cloud-config
package_update: true
package_upgrade: false
preserve_hostname: false
hostname: boutique-droplet

packages:
  - docker.io
  - docker-compose-v2
  - ufw
  - htop
  - curl
  - jq

# Create the system user for the boutique server
users:
  - name: boutique
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: docker
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDB2D98TyoRKmi9slFwHrVMnI35goM7EF3o+CzoxovP4 idp-deploy


runcmd:
#enable docker to start on boot
  - systemctl enable docker
  - systemctl start docker

# basic sysctl sercurity hardening
  - sysctl -w net.ipv4.conf.all.rp_filter=1
  - sysctl -w net.ipv4.conf.all.accept_source_route=0


output:
  all: "| tee -a /var/log/cloud-init-output.log"